export const formForTable = [
  {
    parameter: "Qж",
    parameterCode: "Qz",
    approval: "",
    last: null,
    diff: null,
    accept: null,
  },
  {
    parameter: "% воды",
    parameterCode: "w",
    approval: "",
    last: null,
    diff: null,
    accept: null,
  },
  {
    parameter: "Qн",
    parameterCode: "Qn",
    approval: "",
    last: null,
    diff: null,
    disabled: true,
  },
  {
    parameter: "Hд",
    parameterCode: "Hd",
    approval: "",
    last: null,
    diff: null,
  },
  {
    parameter: "Pлин",
    parameterCode: "Pl",
    approval: "",
    last: null,
    diff: null,
  },
  {
    parameter: "Pбуф",
    parameterCode: "Pb",
    approval: "",
    last: null,
    diff: null,
  },
  {
    parameter: "Pзатр",
    parameterCode: "Pz",
    approval: "",
    last: null,
    diff: null,
  },
];
